name: Daily Knowledge Sync Job

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync job
        run: python -m app.main
        env:
          GEMINI_MODEL: gemini-2.5-flash
          MAX_ARTICLES: 100
          MAX_UPLOAD_FILES: 40
          BASE_URL: https://support.optisigns.com/api/v2/help_center/articles.json

          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FILE_SEARCH_STORE_NAME: ${{ secrets.FILE_SEARCH_STORE_NAME }}